allowBuilds:
{%- if dkcutter.useTriggerDev %}
  "@depot/cli": true
{%- endif %}
  "@ncontiero/eslint-config": false
{%- if dkcutter.usePrisma %}
  "@prisma/engines": true
{%- endif %}
{%- if dkcutter.useTriggerDev %}
  esbuild: true
{%- endif %}
{%- if dkcutter.usePrisma %}
  prisma: true
{%- endif %}
{%- if dkcutter.useTriggerDev %}
  protobufjs: true
{%- endif %}
  sharp: true
  unrs-resolver: true

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
- "@ncontiero/eslint-config@8.4.1"
